import leyline.build.CheckUpstreamTask
import leyline.build.WriteClasspathTask

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.kotlin.power.assert)
    alias(libs.plugins.spotless)
    alias(libs.plugins.detekt)
    id("org.gradle.test-retry")
    alias(libs.plugins.versions)
    jacoco
    application
}

group = "leyline"
version = "0.1.0-SNAPSHOT"

subprojects {
    apply(plugin = "io.gitlab.arturbosch.detekt")
    configure<io.gitlab.arturbosch.detekt.extensions.DetektExtension> {
        buildUponDefaultConfig = true
        config.setFrom(rootProject.files("gradle/detekt.yml"))
        baseline = file("detekt-baseline.xml")
        parallel = true
    }
}

repositories {
    mavenCentral()
    maven {
        url = uri("${rootProject.projectDir}/forge/.m2-local")
        content {
            includeGroup("forge")
        }
    }
}

kotlin {
    jvmToolchain(17)
    compilerOptions {
        freeCompilerArgs.add("-Xjsr305=strict")
    }
}

// Root module sources live in app/ (not default src/) so modules group visually in the tree.
sourceSets {
    main {
        kotlin.setSrcDirs(listOf("app/main/kotlin"))
        resources.setSrcDirs(listOf("app/main/resources"))
    }
    test {
        kotlin.setSrcDirs(listOf("app/test/kotlin"))
        resources.setSrcDirs(listOf("app/test/resources"))
    }
}

dependencies {
    implementation(project(":account"))
    implementation(project(":frontdoor"))
    implementation(project(":matchdoor"))
    implementation(project(":tooling"))
    implementation(libs.kotlin.stdlib)
    implementation(libs.serialization.json)
    implementation(libs.exposed.core)
    implementation(libs.exposed.jdbc)
    implementation(libs.sqlite.jdbc)
    implementation(libs.netty.handler)
    implementation(libs.netty.codec)
    implementation(libs.bouncycastle.pkix)
    implementation(libs.logback.classic)
    implementation(libs.sentry.logback)

    testImplementation(libs.kotest.runner)
    testImplementation(libs.kotest.assertions)
}

// --- Upstream JAR freshness check ---

val checkUpstream by tasks.registering(CheckUpstreamTask::class) {
    description = "Verify forge submodule JARs are installed and current"
    stampFile.set(layout.projectDirectory.file(".upstream-installed"))
    forgeDir.set(rootProject.file("forge").absolutePath)
}

tasks.named("compileKotlin") {
    dependsOn(checkUpstream)
}

// --- Code quality ---

spotless {
    kotlin {
        target("app/**/*.kt")
        ktlint("1.3.1").editorConfigOverride(
            mapOf("ktlint_standard_no-wildcard-imports" to "disabled"),
        )
    }
}

powerAssert {
    functions = listOf(
        "kotlin.assert",
        "kotlin.test.assertTrue",
        "kotlin.test.assertFalse",
        "kotlin.test.assertNull",
        "kotlin.test.assertEquals",
    )
}

detekt {
    buildUponDefaultConfig = true
    config.setFrom(files("gradle/detekt.yml"))
    baseline = file("gradle/detekt-baseline.xml")
    parallel = true
    source.setFrom(files("app/main/kotlin", "app/test/kotlin"))
}

// --- JaCoCo ---
// Per-module reports generated by leyline.test-conventions plugin.
// CI collects all **/jacocoTestReport.xml and ci-report.py merges them.
// Local: `just coverage` runs tests + prints summary from per-module XMLs.

jacoco {
    toolVersion = "0.8.12"
}

tasks.jacocoTestReport {
    reports {
        xml.required.set(true)
    }
}

// --- Application ---

application {
    mainClass.set("leyline.LeylineMainKt")
    applicationDefaultJvmArgs = listOf(
        "-Dio.netty.tryReflectionSetAccessible=true",
        "--add-opens", "java.base/jdk.internal.misc=ALL-UNNAMED",
        "--add-opens", "java.base/java.nio=ALL-UNNAMED",
    )
}

// --- Classpath file (for justfile launch helpers) ---

val writeClasspath by tasks.registering(WriteClasspathTask::class) {
    classpath.set(configurations.runtimeClasspath.map { it.asPath })
    outputFile.set(layout.projectDirectory.file("target/classpath.txt"))
}

tasks.named("classes") {
    finalizedBy(writeClasspath)
}
