package leyline.game

/** Annotation detail key constants — single source of truth for proto detail key strings. */
object DetailKeys {
    const val ZONE_SRC = "zone_src"
    const val ZONE_DEST = "zone_dest"
    const val CATEGORY = "category"
    const val GRPID = "grpid"
    const val PHASE = "phase"
    const val STEP = "step"
    const val ORIG_ID = "orig_id"
    const val NEW_ID = "new_id"
    const val ACTION_TYPE = "actionType"
    const val ABILITY_GRP_ID = "abilityGrpId"
    const val ID = "id"
    const val COLOR = "color"
    const val TAPPED = "tapped"
    const val SOURCE_ZONE = "source_zone"
    const val DAMAGE = "damage"
    const val TYPE = "type"
    const val MARK_DAMAGE = "markDamage"
    const val LIFE = "life"
    const val REASON = "reason"
    const val COUNTER_TYPE = "counter_type"
    const val TRANSACTION_AMOUNT = "transaction_amount"
    const val TOP_COUNT = "topCount"
    const val BOTTOM_COUNT = "bottomCount"
    const val COUNT = "count"
    const val EFFECT_ID = "effect_id"
    const val UNIQUE_ABILITY_ID = "UniqueAbilityId"
    const val ORIGINAL_ABILITY_OBJECT_ZCID = "originalAbilityObjectZcid"
    const val ABILITY_GRP_ID_UPPER = "AbilityGrpId"
    const val USES_REMAINING = "UsesRemaining"
    const val DESIGNATION_TYPE = "DesignationType"
    const val SOURCE_ABILITY_GRPID = "sourceAbilityGRPID"
    const val COLORS = "colors"
    const val INDEX = "index"
    const val PROMPT_ID = "promptId"
    const val PROMPT_PARAMETERS = "promptParameters"
    const val POWER = "power"
    const val TOUGHNESS = "toughness"
    const val DISABLE = "Disable"
    const val TEMPORARY_ZONE_TRANSFER = "TemporaryZoneTransfer"
    const val VALUE = "value"
}
