/**
 * Catalog writer — YAML rendering, dictionaries, and index README for `scry catalog`.
 *
 * Renders AnnotationProfile / PromptProfile / ActionProfile to YAML files,
 * preserving hand-written `notes:` blocks across regeneration. Also builds
 * dictionary lookups for known enum values and renders a markdown index.
 */

import { writeFileSync, mkdirSync, readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import type {
  AnnotationProfile,
  PromptProfile,
  ActionProfile,
  AnnotationInstance,
} from "./catalog-builder";

// --- Types ---

export interface WriteResult {
  written: string[];
  unchanged: string[];
}

export interface Dictionaries {
  [dictName: string]: Record<string, string | null>;
}

// --- Seed data (from rosetta.md) ---

const SEED: Record<string, Record<string, string>> = {
  counter_type: {
    "1": "+1/+1",
    "2": "-1/-1",
    "3": "loyalty",
    "4": "poison",
    "5": "stun",
    "139": "lifelink",
    "42": "shield",
  },
  zone_transfer_category: {
    "6": "CastSpell",
    "7": "PlayLand",
    "8": "Return",
    "9": "Countered",
    "10": "Draw",
    "11": "Discard",
    "13": "Resolve",
    "14": "Search",
    "16": "Exile",
    "17": "Destroy",
    "18": "Sacrifice",
    "19": "Put",
    "20": "SBA_ZeroToughness",
    "21": "SBA_Damage",
    "32": "Bounce",
    "33": "Mill",
    "34": "LibToExile",
  },
  damage_type: {
    "1": "combat",
    "2": "noncombat",
  },
  designation_type: {
    "1": "Commander",
  },
  mana_color: {
    "1": "White",
    "2": "Blue",
    "3": "Black",
    "4": "Red",
    "5": "Green",
  },
};

/** Map from annotation detail key → dictionary name (when they differ). */
const KEY_TO_DICT: Record<string, string> = {
  counter_type: "counter_type",
  category: "zone_transfer_category",
  designation_type: "designation_type",
  color: "mana_color",
  // "type" → damage_type, but ONLY inside DamageDealt — handled specially
};

// --- YAML header ---

const YAML_HEADER = "# auto-generated by scry catalog — do not edit except `notes:` field\n";

// --- Notes round-trip ---

/**
 * Extract the `notes:` block scalar content from existing YAML.
 * Returns empty string if no notes block found.
 */
export function preserveNotes(existing: string): string {
  const match = existing.match(/^notes:\s*\|\n([\s\S]*)/m);
  if (!match) return "";
  // The block scalar content is everything after `notes: |\n`, indented by 2 spaces
  const lines = match[1].split("\n");
  const noteLines: string[] = [];
  for (const line of lines) {
    // Block scalar lines are indented (or empty)
    if (line.startsWith("  ") || line === "") {
      noteLines.push(line.startsWith("  ") ? line.slice(2) : line);
    } else {
      break; // next top-level key or end of file
    }
  }
  // Trim trailing empty lines
  while (noteLines.length > 0 && noteLines[noteLines.length - 1] === "") {
    noteLines.pop();
  }
  return noteLines.join("\n");
}

// --- YAML helpers ---

function yamlArray(items: string[]): string {
  if (items.length === 0) return "[]";
  return "[" + items.map((i) => JSON.stringify(i)).join(", ") + "]";
}

function yamlValueSamples(samples: Record<string, Set<string>>): string {
  const keys = Object.keys(samples).sort();
  if (keys.length === 0) return "value_samples: {}\n";
  let out = "value_samples:\n";
  for (const key of keys) {
    const vals = [...samples[key]].slice(0, 5);
    out += `  ${key}: ${yamlArray(vals)}\n`;
  }
  return out;
}

function yamlNotesBlock(notes: string): string {
  if (!notes) return "notes: |\n";
  return "notes: |\n" + notes.split("\n").map((l) => `  ${l}`).join("\n") + "\n";
}

// --- Annotation YAML ---

export function renderAnnotationYaml(
  profile: AnnotationProfile,
  existingContent?: string,
): string {
  const notes = existingContent ? preserveNotes(existingContent) : "";

  let out = YAML_HEADER;
  out += `type: ${profile.type}\n`;
  out += `instances: ${profile.instances}\n`;
  out += `games: ${profile.games}\n`;
  out += `persistence: ${profile.persistence}\n`;
  out += `always_keys: ${yamlArray(profile.alwaysKeys)}\n`;

  if (profile.sometimesKeys.length === 0) {
    out += "sometimes_keys: []\n";
  } else {
    out += "sometimes_keys:\n";
    for (const sk of profile.sometimesKeys) {
      out += `  - key: ${JSON.stringify(sk.key)}\n`;
      out += `    pct: ${sk.pct}\n`;
    }
  }

  out += yamlValueSamples(profile.valueSamples);

  // Cards
  out += "cards:\n";
  out += `  count: ${profile.cards.count}\n`;
  if (profile.cards.notable.length === 0) {
    out += "  notable: []\n";
  } else {
    out += "  notable:\n";
    for (const n of profile.cards.notable) {
      out += `    - { grp: ${n.grp}, name: ${JSON.stringify(n.name)}, context: ${JSON.stringify(n.context)} }\n`;
    }
  }

  // Co-types: sorted by count desc
  const coTypeSorted = [...profile.coTypes.entries()].sort((a, b) => b[1] - a[1]);
  const coTypeNames = coTypeSorted.map(([name]) => name);
  out += `co_types: ${yamlArray(coTypeNames)}\n`;

  out += `first_seen: ${profile.firstSeen ?? "null"}\n`;
  out += `last_seen: ${profile.lastSeen ?? "null"}\n`;
  out += yamlNotesBlock(notes);

  return out;
}

// --- Prompt YAML ---

export function renderPromptYaml(
  profile: PromptProfile,
  existingContent?: string,
): string {
  const notes = existingContent ? preserveNotes(existingContent) : "";

  let out = YAML_HEADER;
  out += `type: ${profile.type}\n`;
  out += `occurrences: ${profile.occurrences}\n`;
  out += `games: ${profile.games}\n`;
  out += `always_fields: ${yamlArray(profile.alwaysFields)}\n`;

  if (profile.sometimesFields.length === 0) {
    out += "sometimes_fields: []\n";
  } else {
    out += "sometimes_fields:\n";
    for (const sf of profile.sometimesFields) {
      out += `  - field: ${JSON.stringify(sf.field)}\n`;
      out += `    pct: ${sf.pct}\n`;
    }
  }

  out += `first_seen: ${profile.firstSeen ?? "null"}\n`;
  out += `last_seen: ${profile.lastSeen ?? "null"}\n`;
  out += yamlNotesBlock(notes);

  return out;
}

// --- Action YAML ---

export function renderActionYaml(
  profile: ActionProfile,
  existingContent?: string,
): string {
  const notes = existingContent ? preserveNotes(existingContent) : "";

  let out = YAML_HEADER;
  out += `type: ${profile.type}\n`;
  out += `occurrences: ${profile.occurrences}\n`;
  out += `games: ${profile.games}\n`;
  out += `always_fields: ${yamlArray(profile.alwaysFields)}\n`;

  if (profile.sometimesFields.length === 0) {
    out += "sometimes_fields: []\n";
  } else {
    out += "sometimes_fields:\n";
    for (const sf of profile.sometimesFields) {
      out += `  - field: ${JSON.stringify(sf.field)}\n`;
      out += `    pct: ${sf.pct}\n`;
    }
  }

  out += `first_seen: ${profile.firstSeen ?? "null"}\n`;
  out += `last_seen: ${profile.lastSeen ?? "null"}\n`;
  out += yamlNotesBlock(notes);

  return out;
}

// --- File I/O ---

function ensureDir(dir: string): void {
  mkdirSync(dir, { recursive: true });
}

function writeIfChanged(filePath: string, content: string): boolean {
  if (existsSync(filePath)) {
    const existing = readFileSync(filePath, "utf-8");
    if (existing === content) return false;
  }
  writeFileSync(filePath, content);
  return true;
}

function readExisting(filePath: string): string | undefined {
  if (!existsSync(filePath)) return undefined;
  return readFileSync(filePath, "utf-8");
}

export function writeAnnotations(
  profiles: Map<string, AnnotationProfile>,
  outDir: string,
): WriteResult {
  const dir = join(outDir, "annotations");
  ensureDir(dir);
  const written: string[] = [];
  const unchanged: string[] = [];

  for (const [type, profile] of profiles) {
    const filePath = join(dir, `${type}.yaml`);
    const existing = readExisting(filePath);
    const yaml = renderAnnotationYaml(profile, existing);
    if (writeIfChanged(filePath, yaml)) {
      written.push(filePath);
    } else {
      unchanged.push(filePath);
    }
  }

  return { written, unchanged };
}

export function writePrompts(
  profiles: Map<string, PromptProfile>,
  outDir: string,
): WriteResult {
  const dir = join(outDir, "prompts");
  ensureDir(dir);
  const written: string[] = [];
  const unchanged: string[] = [];

  for (const [type, profile] of profiles) {
    const filePath = join(dir, `${type}.yaml`);
    const existing = readExisting(filePath);
    const yaml = renderPromptYaml(profile, existing);
    if (writeIfChanged(filePath, yaml)) {
      written.push(filePath);
    } else {
      unchanged.push(filePath);
    }
  }

  return { written, unchanged };
}

export function writeActions(
  profiles: Map<string, ActionProfile>,
  outDir: string,
): WriteResult {
  const dir = join(outDir, "actions");
  ensureDir(dir);
  const written: string[] = [];
  const unchanged: string[] = [];

  for (const [type, profile] of profiles) {
    const filePath = join(dir, `${type}.yaml`);
    const existing = readExisting(filePath);
    const yaml = renderActionYaml(profile, existing);
    if (writeIfChanged(filePath, yaml)) {
      written.push(filePath);
    } else {
      unchanged.push(filePath);
    }
  }

  return { written, unchanged };
}

// --- Dictionaries (Task 3) ---

/**
 * Scan annotations for dictionary-relevant detail keys.
 * Returns a map from dictionary name → set of observed values.
 */
export function collectDictionaryValues(
  annotations: Map<string, AnnotationInstance[]>,
): Map<string, Set<string>> {
  const observed = new Map<string, Set<string>>();

  for (const [annType, instances] of annotations) {
    for (const inst of instances) {
      for (const [key, val] of Object.entries(inst.values)) {
        let dictName: string | undefined;

        if (key === "type" && annType === "DamageDealt") {
          dictName = "damage_type";
        } else {
          dictName = KEY_TO_DICT[key];
        }

        if (!dictName) continue;

        let set = observed.get(dictName);
        if (!set) {
          set = new Set();
          observed.set(dictName, set);
        }
        set.add(String(val));
      }
    }
  }

  return observed;
}

/**
 * Merge observed values with seed data.
 * Unknown values (observed but not in seed) get null label.
 */
export function buildDictionaries(
  observedValues: Map<string, Set<string>>,
): Dictionaries {
  const result: Dictionaries = {};

  // Start with all seed dictionaries
  for (const [dictName, seedEntries] of Object.entries(SEED)) {
    result[dictName] = { ...seedEntries };
  }

  // Merge observed values
  for (const [dictName, values] of observedValues) {
    if (!result[dictName]) {
      result[dictName] = {};
    }
    for (const val of values) {
      if (!(val in result[dictName])) {
        result[dictName][val] = null; // unknown
      }
    }
  }

  return result;
}

export function renderDictionariesYaml(dict: Dictionaries): string {
  let out = YAML_HEADER;

  const dictNames = Object.keys(dict).sort();
  for (const name of dictNames) {
    out += `${name}:\n`;
    const entries = dict[name];
    // Sort keys numerically
    const keys = Object.keys(entries).sort((a, b) => Number(a) - Number(b));
    for (const key of keys) {
      const label = entries[key];
      if (label === null) {
        out += `  "${key}": null  # unknown — observed in corpus\n`;
      } else {
        out += `  "${key}": ${JSON.stringify(label)}\n`;
      }
    }
  }

  return out;
}

export function writeDictionaries(dict: Dictionaries, outDir: string): void {
  ensureDir(outDir);
  const filePath = join(outDir, "dictionaries.yaml");
  writeFileSync(filePath, renderDictionariesYaml(dict));
}

// --- Index README (Task 4) ---

export function renderIndexReadme(
  annotations: Map<string, AnnotationProfile>,
  prompts: Map<string, PromptProfile>,
  actions: Map<string, ActionProfile>,
  gameCount: number,
  gsmCount: number,
): string {
  let out = "# Protocol Catalog\n\n";
  out += `Corpus: ${gameCount} games, ${gsmCount} game state messages.\n\n`;

  // Annotations table — sorted by instances desc
  const annSorted = [...annotations.values()].sort((a, b) => b.instances - a.instances);
  out += "## Annotations\n\n";
  out += "| Type | Instances | Games | Persistence | Always keys |\n";
  out += "|------|-----------|-------|-------------|-------------|\n";
  for (const p of annSorted) {
    const keys = p.alwaysKeys.length > 0 ? p.alwaysKeys.join(", ") : "—";
    out += `| ${p.type} | ${p.instances} | ${p.games} | ${p.persistence} | ${keys} |\n`;
  }

  // Prompts table — sorted by occurrences desc
  const promptSorted = [...prompts.values()].sort((a, b) => b.occurrences - a.occurrences);
  out += "\n## Prompts\n\n";
  out += "| Type | Occurrences | Games | Always fields |\n";
  out += "|------|-------------|-------|---------------|\n";
  for (const p of promptSorted) {
    const fields = p.alwaysFields.length > 0 ? p.alwaysFields.join(", ") : "—";
    out += `| ${p.type} | ${p.occurrences} | ${p.games} | ${fields} |\n`;
  }

  // Actions table — sorted by occurrences desc
  const actionSorted = [...actions.values()].sort((a, b) => b.occurrences - a.occurrences);
  out += "\n## Actions\n\n";
  out += "| Type | Occurrences | Games | Always fields |\n";
  out += "|------|-------------|-------|---------------|\n";
  for (const p of actionSorted) {
    const fields = p.alwaysFields.length > 0 ? p.alwaysFields.join(", ") : "—";
    out += `| ${p.type} | ${p.occurrences} | ${p.games} | ${fields} |\n`;
  }

  return out;
}

export function writeIndex(
  annotations: Map<string, AnnotationProfile>,
  prompts: Map<string, PromptProfile>,
  actions: Map<string, ActionProfile>,
  gameCount: number,
  gsmCount: number,
  outDir: string,
): void {
  ensureDir(outDir);
  const filePath = join(outDir, "README.md");
  writeFileSync(filePath, renderIndexReadme(annotations, prompts, actions, gameCount, gsmCount));
}
