import { describe, expect, it } from "bun:test";
import {
  renderAnnotationYaml,
  renderPromptYaml,
  renderActionYaml,
  preserveNotes,
  buildDictionaries,
  renderDictionariesYaml,
  collectDictionaryValues,
  renderIndexReadme,
} from "./catalog-writer";
import type {
  AnnotationProfile,
  PromptProfile,
  ActionProfile,
  AnnotationInstance,
} from "./catalog-builder";

// --- Helpers ---

function makeAnnotationProfile(overrides?: Partial<AnnotationProfile>): AnnotationProfile {
  return {
    type: "CounterAdded",
    instances: 23,
    games: 8,
    persistence: "transient",
    alwaysKeys: ["counter_type", "transaction_amount"],
    sometimesKeys: [{ key: "some_rare_key", pct: 15 }],
    valueSamples: {
      counter_type: new Set(["1", "139", "42"]),
      transaction_amount: new Set(["1", "2", "3"]),
    },
    cards: {
      count: 9,
      notable: [
        { grp: 84262, name: "Enduring Bondwarden", context: 'counter_type=1 (backup)' },
      ],
    },
    coTypes: new Map([
      ["PowerToughnessModCreated", 20],
      ["Counter", 15],
    ]),
    firstSeen: "2026-03-29",
    lastSeen: "2026-04-04",
    ...overrides,
  };
}

function makePromptProfile(overrides?: Partial<PromptProfile>): PromptProfile {
  return {
    type: "SelectNReq",
    occurrences: 45,
    games: 12,
    alwaysFields: ["minSel", "maxSel"],
    sometimesFields: [{ field: "prompt", pct: 80 }],
    firstSeen: "2026-03-29",
    lastSeen: "2026-04-04",
    ...overrides,
  };
}

function makeActionProfile(overrides?: Partial<ActionProfile>): ActionProfile {
  return {
    type: "Cast",
    occurrences: 100,
    games: 20,
    alwaysFields: ["instanceId", "grpId"],
    sometimesFields: [{ field: "manaCost", pct: 60 }],
    firstSeen: "2026-03-29",
    lastSeen: "2026-04-04",
    ...overrides,
  };
}

// --- Task 2: YAML rendering ---

describe("renderAnnotationYaml", () => {
  it("produces expected shape", () => {
    const profile = makeAnnotationProfile();
    const yaml = renderAnnotationYaml(profile);

    expect(yaml).toContain("# auto-generated by scry catalog");
    expect(yaml).toContain("type: CounterAdded");
    expect(yaml).toContain("instances: 23");
    expect(yaml).toContain("games: 8");
    expect(yaml).toContain("persistence: transient");
    expect(yaml).toContain('always_keys: ["counter_type", "transaction_amount"]');
    expect(yaml).toContain("sometimes_keys:");
    expect(yaml).toContain('  - key: "some_rare_key"');
    expect(yaml).toContain("    pct: 15");
    expect(yaml).toContain("value_samples:");
    expect(yaml).toContain("cards:");
    expect(yaml).toContain("  count: 9");
    expect(yaml).toContain("notable:");
    expect(yaml).toContain("grp: 84262");
    expect(yaml).toContain("co_types:");
    expect(yaml).toContain("first_seen: 2026-03-29");
    expect(yaml).toContain("last_seen: 2026-04-04");
    expect(yaml).toContain("notes: |");
  });
});

describe("renderPromptYaml", () => {
  it("produces expected shape", () => {
    const yaml = renderPromptYaml(makePromptProfile());

    expect(yaml).toContain("type: SelectNReq");
    expect(yaml).toContain("occurrences: 45");
    expect(yaml).toContain("games: 12");
    expect(yaml).toContain('always_fields: ["minSel", "maxSel"]');
    expect(yaml).toContain("sometimes_fields:");
    expect(yaml).toContain('  - field: "prompt"');
    expect(yaml).toContain("notes: |");
  });
});

describe("renderActionYaml", () => {
  it("produces expected shape", () => {
    const yaml = renderActionYaml(makeActionProfile());

    expect(yaml).toContain("type: Cast");
    expect(yaml).toContain("occurrences: 100");
    expect(yaml).toContain('always_fields: ["instanceId", "grpId"]');
    expect(yaml).toContain("sometimes_fields:");
    expect(yaml).toContain("notes: |");
  });
});

// --- Notes round-trip ---

describe("preserveNotes", () => {
  it("extracts notes from existing YAML", () => {
    const yaml = [
      "type: Foo",
      "instances: 10",
      "notes: |",
      "  Hand-written notes here.",
      "  Second line of notes.",
      "",
    ].join("\n");

    const notes = preserveNotes(yaml);
    expect(notes).toBe("Hand-written notes here.\nSecond line of notes.");
  });

  it("returns empty string when no notes", () => {
    const yaml = "type: Foo\ninstances: 10\n";
    expect(preserveNotes(yaml)).toBe("");
  });

  it("returns empty string for empty notes block", () => {
    const yaml = "type: Foo\nnotes: |\n";
    expect(preserveNotes(yaml)).toBe("");
  });
});

describe("notes round-trip", () => {
  it("preserves hand-written notes across regeneration", () => {
    const profile = makeAnnotationProfile();

    // First render — no notes
    const yaml1 = renderAnnotationYaml(profile);
    expect(yaml1).toContain("notes: |");

    // Simulate hand-editing: add notes
    const edited = yaml1.replace("notes: |\n", "notes: |\n  Important finding about CounterAdded.\n");

    // Re-render with existing content — notes preserved
    const yaml2 = renderAnnotationYaml(profile, edited);
    expect(yaml2).toContain("notes: |");
    expect(yaml2).toContain("  Important finding about CounterAdded.");
  });
});

// --- Task 3: Dictionaries ---

describe("collectDictionaryValues", () => {
  it("collects values from dictionary-relevant keys", () => {
    const annotations = new Map<string, AnnotationInstance[]>();
    annotations.set("CounterAdded", [
      {
        type: "CounterAdded",
        keys: ["counter_type"],
        values: { counter_type: 1 },
        isPersistent: false,
        gameLabel: "g1",
        gsmId: 1,
        affectorId: 100,
        affectedIds: [],
        coTypes: [],
      },
      {
        type: "CounterAdded",
        keys: ["counter_type"],
        values: { counter_type: 999 },
        isPersistent: false,
        gameLabel: "g1",
        gsmId: 2,
        affectorId: 101,
        affectedIds: [],
        coTypes: [],
      },
    ]);
    annotations.set("DamageDealt", [
      {
        type: "DamageDealt",
        keys: ["type"],
        values: { type: 1 },
        isPersistent: false,
        gameLabel: "g1",
        gsmId: 3,
        affectorId: 102,
        affectedIds: [],
        coTypes: [],
      },
    ]);

    const observed = collectDictionaryValues(annotations);

    expect(observed.get("counter_type")?.has("1")).toBe(true);
    expect(observed.get("counter_type")?.has("999")).toBe(true);
    expect(observed.get("damage_type")?.has("1")).toBe(true);
  });

  it("does not map 'type' key outside DamageDealt", () => {
    const annotations = new Map<string, AnnotationInstance[]>();
    annotations.set("SomeOther", [
      {
        type: "SomeOther",
        keys: ["type"],
        values: { type: 1 },
        isPersistent: false,
        gameLabel: "g1",
        gsmId: 1,
        affectorId: undefined,
        affectedIds: [],
        coTypes: [],
      },
    ]);

    const observed = collectDictionaryValues(annotations);
    expect(observed.has("damage_type")).toBe(false);
  });
});

describe("buildDictionaries", () => {
  it("merges observed with seed, unknown values get null", () => {
    const observed = new Map<string, Set<string>>();
    observed.set("counter_type", new Set(["1", "999"]));

    const dict = buildDictionaries(observed);

    // Seed value preserved
    expect(dict.counter_type["1"]).toBe("+1/+1");
    // Unknown value gets null
    expect(dict.counter_type["999"]).toBeNull();
    // Other seed dicts still present
    expect(dict.damage_type["1"]).toBe("combat");
  });
});

describe("renderDictionariesYaml", () => {
  it("produces valid YAML with sorted keys", () => {
    const dict = buildDictionaries(new Map([["counter_type", new Set(["999"])]]));
    const yaml = renderDictionariesYaml(dict);

    expect(yaml).toContain("# auto-generated by scry catalog");
    expect(yaml).toContain("counter_type:");
    expect(yaml).toContain('  "1": "+1/+1"');
    expect(yaml).toContain('  "999": null  # unknown');
    // Keys should be numerically sorted — "1" before "2" before "42"
    const lines = yaml.split("\n");
    const counterLines = lines.filter((l) => l.startsWith('  "') && lines.indexOf(l) > lines.indexOf("counter_type:"));
    // Just verify it contains expected entries
    expect(yaml).toContain("damage_type:");
    expect(yaml).toContain("mana_color:");
  });
});

// --- Task 4: Index README ---

describe("renderIndexReadme", () => {
  it("produces markdown with all three tables", () => {
    const annotations = new Map<string, AnnotationProfile>();
    annotations.set("CounterAdded", makeAnnotationProfile());
    annotations.set("DamageDealt", makeAnnotationProfile({
      type: "DamageDealt",
      instances: 50,
      games: 10,
      persistence: "transient",
      alwaysKeys: ["damage_amount"],
    }));

    const prompts = new Map<string, PromptProfile>();
    prompts.set("SelectNReq", makePromptProfile());

    const actions = new Map<string, ActionProfile>();
    actions.set("Cast", makeActionProfile());

    const md = renderIndexReadme(annotations, prompts, actions, 15, 200);

    // Header
    expect(md).toContain("# Protocol Catalog");
    expect(md).toContain("Corpus: 15 games, 200 game state messages.");

    // Annotations table
    expect(md).toContain("## Annotations");
    expect(md).toContain("| Type | Instances | Games | Persistence | Always keys |");
    expect(md).toContain("| DamageDealt | 50 |"); // higher count first
    expect(md).toContain("| CounterAdded | 23 |");

    // Prompts table
    expect(md).toContain("## Prompts");
    expect(md).toContain("| Type | Occurrences | Games | Always fields |");
    expect(md).toContain("| SelectNReq | 45 |");

    // Actions table
    expect(md).toContain("## Actions");
    expect(md).toContain("| Cast | 100 |");
  });
});
