package leyline.game.mapping

import leyline.game.annotations.AnnotationBuilder
import leyline.game.annotations.AnnotationConstants
import wotc.mtgo.gre.external.messaging.Messages.AnnotationInfo

/**
 * State-tail diff for the game-scope Day/Night state primitive. Compares
 * `prev.dayTime` to `cur.dayTime` and emits the matching transient
 * `GainDesignation` / `LoseDesignation` lite-shape annotations on the game.
 *
 * Three transitions:
 *  - **neither → Day** (cur=false): one `GainDesignation{Day}`. Pre-state has
 *    no Day/Night designation, so no paired lose.
 *  - **neither → Night** (cur=true): one `GainDesignation{Night}`. Symmetric
 *    to the Day case — covers "becomes night" effects out of the gate
 *    (CR 731.1).
 *  - **Day ↔ Night flip** (prev=false→cur=true or true→false): outgoing
 *    state's `LoseDesignation` paired with incoming state's `GainDesignation`.
 *
 * The persistent `Designation` re-emission lives on the snapshot path —
 * `dayNightDesignationPersistentFromSnap` in [StateMapper.buildFromSnapshot]
 * does its own thing there, so this function only handles the transient
 * change-edge annotations. Both gain and lose append at end of list — the
 * lifecycle bracket on the daybound creature ETB is already structurally
 * positioned via the ResolutionStart/Complete + ZoneTransfer annotations
 * generated by the broader pipeline.
 *
 * No-op when prev.dayTime == cur.dayTime — the persistent re-emit covers
 * APSC ticks without us touching transient annotations.
 */
internal fun insertDayNightDesignationTransients(
    annotations: MutableList<AnnotationInfo>,
    prevDayTime: Boolean?,
    curDayTime: Boolean?,
) {
    if (prevDayTime == curDayTime) return
    if (prevDayTime != null) {
        annotations.add(
            AnnotationBuilder.loseDesignationOnGame(
                designationType = designationTypeOf(prevDayTime),
            ),
        )
    }
    if (curDayTime != null) {
        annotations.add(
            AnnotationBuilder.gainDesignationOnGame(
                designationType = designationTypeOf(curDayTime),
            ),
        )
    }
}

private fun designationTypeOf(isNight: Boolean): Int =
    if (isNight) {
        AnnotationConstants.DESIGNATION_TYPE_NIGHT
    } else {
        AnnotationConstants.DESIGNATION_TYPE_DAY
    }
